# Generated by Django 2.1.1 on 2018-11-16 06:38

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, verbose_name='账号')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后回复时间')),
                ('status', models.CharField(choices=[('Closed.', '已关闭'), ('Open.', '开放中')], default=('Open.', '开放中'), max_length=20, verbose_name='帖子状态')),
                ('view', models.IntegerField(default=1, verbose_name='浏览量')),
                ('reply', models.IntegerField(default=0, verbose_name='回复量')),
                ('content_html', DjangoUeditor.models.UEditorField(verbose_name='文章内容')),
                ('is_top', models.BooleanField(default=True, verbose_name='是否置顶')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.MyUser', verbose_name='作者')),
            ],
        ),
    ]
