# Generated by Django 2.1.3 on 2018-11-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='mailnotify',
            field=models.BooleanField(default=False),
        ),
    ]
