# Generated by Django 2.1.1 on 2018-11-16 11:52

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_html', DjangoUeditor.models.UEditorField(verbose_name='文章内容')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pk', to='bbs.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.MyUser')),
            ],
        ),
    ]
