# Generated by Django 2.1.1 on 2018-11-16 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='post',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
