# Generated by Django 2.1.3 on 2018-12-08 16:17

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20181122_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Martor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', martor.models.MartorField()),
                ('wiki', martor.models.MartorField()),
            ],
        ),
    ]
