# Generated by Django 2.1.1 on 2018-11-15 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('last_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后回复时间')),
                ('status', models.CharField(choices=[('Closed', '已关闭'), ('Open.', '开放中')], default=('Open.', '开放中'), max_length=20, verbose_name='帖子状态')),
                ('creator_id', models.IntegerField(verbose_name='创建者ID')),
                ('view', models.IntegerField(default=1, verbose_name='浏览量')),
                ('reply', models.IntegerField(default=0, verbose_name='回复量')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_top', models.BooleanField(default=True, verbose_name='是否置顶')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
