# Generated by Django 2.1.3 on 2018-12-08 17:28

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_martor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='content_html',
            field=martor.models.MartorField(verbose_name='回复内容'),
        ),
    ]
