# Generated by Django 2.1.1 on 2018-11-16 14:09

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='content_html',
            field=DjangoUeditor.models.UEditorField(verbose_name='回复内容'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
