# Generated by Django 2.1.3 on 2018-12-08 19:43

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_auto_20181209_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=martor.models.MartorField(verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_html',
            field=martor.models.MartorField(verbose_name='文章内容'),
        ),
    ]
