# Generated by Django 2.1.3 on 2018-12-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0005_auto_20181209_0343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Martor',
        ),
    ]
