# Generated by Django 2.1.1 on 2018-11-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0008_auto_20181116_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content_html',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=1, verbose_name='评论内容'),
            preserve_default=False,
        ),
    ]
