# Generated by Django 2.1.1 on 2018-11-17 16:38

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0009_auto_20181117_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=DjangoUeditor.models.UEditorField(verbose_name='评论内容'),
        ),
    ]
