# Generated by Django 2.1.1 on 2018-11-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0011_auto_20181117_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_html',
            field=models.TextField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content_html',
            field=models.TextField(verbose_name='回复内容'),
        ),
    ]
