# Generated by Django 2.1.1 on 2018-11-18 13:07

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0013_myuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='img/bbs/profile/default.png', upload_to='img/bbs/profile', verbose_name='头像'),
        ),
    ]
