# Generated by Django 2.0.2 on 2018-02-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='实验室简介')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('it_teacher', models.BooleanField(verbose_name='是否是老师')),
                ('title', models.CharField(max_length=50, verbose_name='职称')),
                ('content', models.TextField(verbose_name='个人简介')),
                ('homepage', models.URLField(verbose_name='个人主页')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('research_interests', models.TextField(verbose_name='研究方向')),
                ('status', models.BooleanField(verbose_name='是否在读/职')),
                ('image', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Publictaion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.TextField(verbose_name='作者')),
                ('title', models.TextField(verbose_name='标题')),
                ('link', models.URLField(verbose_name='文章链接')),
                ('suffix', models.TextField(verbose_name='后缀')),
                ('year', models.IntegerField(verbose_name='发表年份')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='方向')),
                ('intro', models.TextField(verbose_name='简介')),
            ],
        ),
    ]
