# Generated by Django 2.1.1 on 2018-11-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='detial',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='research',
            old_name='detial',
            new_name='detail',
        ),
    ]
