# Generated by Django 2.0.2 on 2018-02-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180221_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='title',
            field=models.CharField(max_length=100, verbose_name='方向'),
        ),
    ]
