# Generated by Django 2.0.2 on 2018-02-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180221_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('student_type', models.CharField(choices=[('Ph.D.', '博士生'), ('M.S.', '硕士生'), ('Undergraduates', '本科生')], max_length=20, verbose_name='学生类别')),
                ('status', models.BooleanField(default=True, verbose_name='是否在读')),
                ('homepage', models.URLField(verbose_name='个人主页')),
                ('github', models.URLField(verbose_name='Github')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('research_interests', models.TextField(default='强化学习；深度学习；', verbose_name='研究方向')),
                ('image', models.ImageField(upload_to='img/member', verbose_name='个人照片')),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
