# Generated by Django 2.0.2 on 2018-02-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180223_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('Ph.D.', '博士生'), ('M.S.', '硕士生'), ('Undergraduates', '本科生')], default=('Ph.D.', '博士生'), max_length=20, verbose_name='学生类别'),
        ),
    ]
