# Generated by Django 2.0.2 on 2018-02-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180223_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='student',
            name='github',
            field=models.URLField(null=True, verbose_name='Github'),
        ),
        migrations.AlterField(
            model_name='student',
            name='homepage',
            field=models.URLField(null=True, verbose_name='个人主页'),
        ),
        migrations.AlterField(
            model_name='student',
            name='research_interests',
            field=models.TextField(default='强化学习；深度学习；', null=True, verbose_name='研究方向'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('Ph.D.', '博士生'), ('M.S.', '硕士生'), ('Undergraduates', '本科生')], default=('Undergraduates', '本科生'), max_length=20, verbose_name='学生类别'),
        ),
    ]
