# Generated by Django 2.0.2 on 2018-02-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20180223_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=2018, verbose_name='入学年份'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, default=2014, max_length=254, verbose_name='邮箱'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='github',
            field=models.URLField(blank=True, verbose_name='Github'),
        ),
        migrations.AlterField(
            model_name='student',
            name='homepage',
            field=models.URLField(blank=True, verbose_name='个人主页'),
        ),
        migrations.AlterField(
            model_name='student',
            name='research_interests',
            field=models.TextField(blank=True, default='强化学习；深度学习；', verbose_name='研究方向'),
        ),
    ]
