# Generated by Django 2.0.2 on 2018-02-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20180223_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='tag1',
            field=models.CharField(blank=True, max_length=20, verbose_name='标签一'),
        ),
        migrations.AddField(
            model_name='research',
            name='tag2',
            field=models.CharField(blank=True, max_length=20, verbose_name='标签二'),
        ),
        migrations.AddField(
            model_name='research',
            name='tag3',
            field=models.CharField(blank=True, max_length=20, verbose_name='标签三'),
        ),
    ]
