# Generated by Django 2.0.2 on 2018-02-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20180223_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
    ]
