# Generated by Django 2.0.2 on 2018-02-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20180223_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='image',
            field=models.ImageField(default='', upload_to='img/research', verbose_name='个人照片'),
            preserve_default=False,
        ),
    ]
