# Generated by Django 2.0.2 on 2018-02-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_research_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='image',
            field=models.ImageField(upload_to='img/research', verbose_name='图片'),
        ),
    ]
