# Generated by Django 2.0.2 on 2018-02-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20180223_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='link',
            field=models.URLField(blank=True, verbose_name='链接'),
        ),
    ]
