# Generated by Django 2.0.2 on 2018-03-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_research_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publictaion',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='publictaion',
            name='suffix',
        ),
        migrations.AddField(
            model_name='publictaion',
            name='code',
            field=models.URLField(default=2018, verbose_name='代码链接'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publictaion',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
    ]
