# Generated by Django 2.0.2 on 2018-03-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20180317_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictaion',
            name='code',
            field=models.URLField(blank=True, verbose_name='代码链接'),
        ),
        migrations.AlterField(
            model_name='publictaion',
            name='link',
            field=models.URLField(blank=True, verbose_name='文章链接'),
        ),
    ]
