# Generated by Django 2.0.2 on 2018-06-20 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20180317_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='标题')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期')),
            ],
        ),
    ]
