# Generated by Django 2.0.2 on 2018-06-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='News_type',
            field=models.CharField(choices=[('Paper', 'Paper'), ('Application', 'Application'), ('News', 'News')], default=('News', 'News'), max_length=20, verbose_name='新闻类别'),
        ),
    ]
