# Generated by Django 2.0.2 on 2018-06-20 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_news_news_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='News_type',
            new_name='news_type',
        ),
    ]
