# Generated by Django 2.0.2 on 2018-08-18 12:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20180620_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(verbose_name='正文')),
            ],
        ),
    ]
