# Generated by Django 2.0.2 on 2018-08-19 06:10

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_editortest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期')),
                ('view', models.IntegerField(default=1, verbose_name='浏览量')),
                ('text', ckeditor.fields.RichTextField(verbose_name='正文')),
            ],
        ),
        migrations.DeleteModel(
            name='EditorTest',
        ),
    ]
