# Generated by Django 2.0.2 on 2018-08-19 06:16

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20180819_1410'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detial',
        ),
        migrations.AddField(
            model_name='news',
            name='detial',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now, verbose_name='正文'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='view',
            field=models.IntegerField(default=1, verbose_name='浏览量'),
        ),
        migrations.AddField(
            model_name='research',
            name='detial',
            field=ckeditor.fields.RichTextField(default=0, verbose_name='正文'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='research',
            name='view',
            field=models.IntegerField(default=1, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='about',
            name='about',
            field=ckeditor.fields.RichTextField(verbose_name='实验室简介'),
        ),
    ]
