# Generated by Django 2.0.2 on 2018-08-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_research_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/carousel', verbose_name='')),
                ('title', models.TextField(verbose_name='简介')),
            ],
        ),
    ]
