# Generated by Django 2.0.2 on 2018-08-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='link',
            field=models.URLField(blank=True, verbose_name='文章链接'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(upload_to='img/carousel', verbose_name='图片'),
        ),
    ]
