# Generated by Django 2.1.1 on 2018-09-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20180819_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=models.TextField(blank=True, verbose_name='简介'),
        ),
    ]
