# Generated by Django 2.1.1 on 2018-10-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_auto_20180927_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='image',
            field=models.ImageField(height_field=600, max_length=2048, upload_to='img/research', verbose_name='图片', width_field=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(height_field=550, max_length=2048, upload_to='img/member', verbose_name='个人照片', width_field=400),
        ),
    ]
