# Generated by Django 2.1.1 on 2018-10-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_auto_20181002_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(height_field=550, upload_to='img/member', verbose_name='个人照片', width_field=400),
        ),
    ]
