# Generated by Django 2.1.1 on 2018-10-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_auto_20181002_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='img/member', verbose_name='个人照片'),
        ),
    ]
