# Generated by Django 2.1.1 on 2018-10-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_auto_20181002_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(help_text='fark', upload_to='img/member', verbose_name='个人照片'),
        ),
    ]
