# Generated by Django 2.1.1 on 2018-10-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_auto_20181002_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='image',
            field=models.ImageField(help_text='必须上传尺寸为500x600的图片，否则显示会有问题。', upload_to='img/research', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(help_text='必须上传尺寸为400x550的图片，否则显示会有问题。', upload_to='img/member', verbose_name='个人照片'),
        ),
    ]
